apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /ping
              port: 8086
          volumeMounts:
            - name: influxdb-pv # influxdb-config 파일 [data] 부분을 보면 데이터가 저장되는 위치를 설정할 수 있다. 디폴트 값이 /var/lib/influxdb 이므로 이 위치 볼륨시킨다.
              mountPath: /var/lib/influxdb
          envFrom: # secret.yaml 에 정의해 놓은 환경변수를 가져온다.
            - secretRef:
                name: influxdb-secret
      volumes:
        - name: influxdb-pv
          persistentVolumeClaim:
            claimName: influxdb-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - port: 8086

