apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-cm
          subPath: datasources.yaml
          mountPath: /usr/share/grafana/conf/provisioning/datasources/datasources.yaml
          readOnly: true
        - name: grafana-cm
          subPath: dashboards.yaml
          mountPath: /usr/share/grafana/conf/provisioning/dashboards/dashboards.yaml
          readOnly: true
      volumes:
      - name: grafana-cm
        configMap:
          name: grafana-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
