apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared # 접근 가능한 클러스터 ip가 minikube ip 하나 이기때문에, 하나로 고정시켜야함
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  - port: 22
    name: ssh
    protocol: TCP
    targetPort: 22

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx	# deployment 이름
  labels:
    app: nginx
spec:
  replicas: 1	# pod 를 몇 개 띄울지
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ft_nginx
        imagePullPolicy: Never
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          - containerPort: 22
            name: ssh
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 2
