apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 20000
          - containerPort: 20001
          - containerPort: 20002
          - containerPort: 20003
        livenessProbe:
          initialDelaySeconds: 2
          tcpSocket:
            port: 21
---

apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - port: 21
      name: ftps-command
    - port: 20000
      name: ftps-pasv1
    - port: 20001
      name: ftps-pasv2
    - port: 20002
      name: ftps-pasv3
    - port: 20003
      name: ftps-pasv4
